@TourPlanner.Api_HostAddress = http://localhost:5044

###

POST {{TourPlanner.Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpass"
}

###

POST {{TourPlanner.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpass"
}

###

GET {{TourPlanner.Api_HostAddress}}/api/tours
Accept: application/json

###

POST {{TourPlanner.Api_HostAddress}}/api/tours
Content-Type: application/json

{
  "userId": 1,
  "name": "Added Tour",
  "description": "A great tour",
  "from": "City A",
  "to": "City B",
  "transportType": 0,
  "distance": 2000,
  "estimatedTime": 120,
  "logs": []
}

###

GET {{TourPlanner.Api_HostAddress}}/api/contacts
Accept: application/json

###

GET {{TourPlanner.Api_HostAddress}}/api/contacts/0
Accept: application/json

###

POST {{TourPlanner.Api_HostAddress}}/api/contacts
Content-Type: application/json

{
  "FirstName": "John",
  "LastName": "Pork",
  "Email": "jonh.pork@gmail.com",
  "PhoneNumber": "+43696112233"
}

###

PUT {{TourPlanner.Api_HostAddress}}/api/contacts/0
Content-Type: application/json
{
  "Id": 0,
  "FirstName": "John",
  "LastName": "Pork",
  "Email": "jonh.pork@gmail.com",
  "PhoneNumber": "+43676445566"
}

###

DELETE {{TourPlanner.Api_HostAddress}}/api/contacts/0

###